# -*- coding: utf-8 -*-
"""02_intermediate/Control Flow for Console.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Apvcz-zIKbQarVlB8cBXBNZyuqPNK7Iy
"""

import random
print("High Low Game")

round = 5

def main():
  print("Welcome to the High Low Game")
  print("****************************")


  your_score = 0

  for i in range(round):
    print("Round",i +1)

    computer_number:int=random.randint(1,100)
    your_number:int=random.randint(1,100)
    print("Your number is ",your_number)

    choice:str=input("Do you think your number will be higher or lower than the computer's number? ")
    higher_and_correct:bool=choice=="higher" and your_number>computer_number
    lower_and_correct:bool=choice=="lower" and your_number<computer_number

    if higher_and_correct or lower_and_correct:
      print("You are correct! The computer\'s number was",computer_number)
      your_score+=1
    else:
      print("That\'s incorrect. The computer\'s number was", computer_number)


    print("Your score is now",your_score)
    print()

  print("Thanks for playing!")

if __name__ == "__main__":
  main()

print("Planetary Weight Calculator")

def main():
  print("Welcome to the Planetary Weight Calculator!")
  print("*******************************************")

earth_weight = float(input("Enter your weight on Earth: "))
gravity_ratio={
    "Mercury":0.38,
    "Venus":0.91,
    "Mars":0.38,
    "Jupiter":2.34,
    "Saturn":1.06,
    "Uranus":0.92,
    "Neptune":1.19
}

print("\n Select a Planet")
for planet in gravity_ratio.keys():
  print(f'-{planet}')

planet_choice:str=input("Enter the name of the Planet: ").title()

if planet_choice in gravity_ratio:
  new_weight = earth_weight * gravity_ratio[planet_choice]
  print(f'Your weight on {planet_choice} is {new_weight:.2f}kg')
else:
  print("Invalid planet choice")

if __name__=="__main__":
 main()

print("LIST AND DICTS")

my_list = ["apple","mango","pear","grapes","peach"]
print(my_list)


def access_element(my_list, index):
  """Returns the Element at the Specified index, or Error messageif out of range."""
  if 0 <= index < len(my_list):
        return f'Element at index {index}: {my_list[index]}'
        return "Index out of range"
def modified_element(my_list,index,new_value):
  """Modifies the Element at the specified index with the new value."""
  if 0 <= index < len(my_list):
    old_value=my_list[index]
    my_list[index]=new_value
    return f'Element at index {index} modified from {old_value} to {new_value}'
  return "Index out of range"


def slice_list(my_list,start_index,end_index):
  """Returns a new list containing the sliced elements."""
  if 0 <= start_index < len(my_list) and 0 <= end_index<=len(my_list):
    return f'Sliced list: {my_list[start_index:end_index]}'
  return "Invalid index range"

def list_game():
  print("\n Welcome to the List Game")

my_list = ["apple","mango","pear","grapes","peach"]
while True:
  print("Current list", my_list)

  print("Select an operation")
  print("1. Access Element")
  print("2. Modified Element")
  print("3. Slice Element")
  print("4. Quit")

  choice = input("Enter your choice (1-4): ")
  if choice == "1":
     index = int(input("Enter the index of the element you want to access: "))
     print(access_element(my_list,index))
  elif choice == "2":
     index = int(input("Enter the index of the element you want to modified: "))
     new_value = input("Enter the new value for the Element: ")
     print(modified_element(my_list,index,new_value))
  elif choice =="3":
     start = int(input("Enter the start index foor the slice"))
     end = int(input("Enter the end index for the slice: "))
     print(slice_list(my_list,start,end))
  elif choice == "4":
     print("Exiting the Game, Thanks for playing.")
     break
  else:
     print("Invalid choice! please Enter a number between 1 to 4. ")

  if __name__ == "__main__":
      list_game()