# -*- coding: utf-8 -*-
"""01_basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-SBuFtWqF76HIgUq6eXo-70JUNMJCEZ
"""

print("00_joke_bot")

PROMPT = "What do you want? "
JOKE = "Here is a joke for you! Panaversity GPT - Sophia is heading out to the grocery store. A programmer tells her: get a liter of milk, and if they have eggs, get 12. Sophia returns with 13 liters of milk. The programmer asks why and Sophia replies: 'because they had eggs'"
SORRY = "Sorry I only tell jokes"

def main():
    user_input = input(PROMPT)

    if user_input.strip().lower() == "joke":
        print(JOKE)
    else:
        print(SORRY)

if __name__ == "__main__":
    main()

"print("01_double_it.")

def main():
  user_value = int(input("Please enter a number: "))
  while user_value<100:
    user_value = user_value * 2
    print(user_value)

if __name__ == "__main__":
  main()

print("02_liftoff")

def main():
  for i in range(10,0,-1):
    print(i,end =" ")
  print("liftof")

if __name__ == "__main__":
  main()

import random

print("03_guess_my_number")

def main():
  secret_number = random.randint(1, 100)
  print("I am thinking of a Digit between 1 to 100....")

  guess = int(input("Enter a guess: "))

  while guess != secret_number:
    if guess > secret_number:
      print("Too High!")
    else:
      print("Too Low!")
    guess = int(input("Enter a guess: "))

  print(f"Congratulations! You guess the right {secret_number}....")

if __name__ =="__main__":
  main()

import random
print("04_random_numbers")


def main():
  for i in range(10):
   num:list[int]= random.randint(1,100)
   print(num)

if __name__ == "__main__":
  main()